Games = {
    [5578556129] = { --Anime-Vanguards
        ["BaseB"] = "https://raw.githubusercontent.com/Sendo-cmd/GCS/main/AV_Boss_Base.lua",
        ["BIgrisSon"] = "https://raw.githubusercontent.com/Sendo-cmd/GCS/main/AV_Boss_Base_IgrisSon.lua",
        ["BaseGem"] = "https://raw.githubusercontent.com/Sendo-cmd/GCS/main/AV_GEM.lua",
        ["Gem2"] = "https://raw.githubusercontent.com/Sendo-cmd/GCS/main/AV_GEM2.lua",
        ["Gem3"] = "https://raw.githubusercontent.com/Sendo-cmd/GCS/main/AV_GEM3.lua",
        ["BaseGemInf"] = "https://raw.githubusercontent.com/Sendo-cmd/GCS/main/AV_GEMINF.lua",
        ["BaseIG"] = "https://raw.githubusercontent.com/Sendo-cmd/GCS/main/AV_IGRIS_Base.lua",
        ["BaseR"] = "https://raw.githubusercontent.com/Sendo-cmd/GCS/main/AV_Rengoku_Base.lua",
        ["RIgris"] = "https://raw.githubusercontent.com/Sendo-cmd/GCS/main/AV_Rengoku_Igris.lua",
        ["RRengoku"] = "https://raw.githubusercontent.com/Sendo-cmd/GCS/main/AV_Rengoku_Renguko.lua",
        ["RAkazo"] = "https://raw.githubusercontent.com/Sendo-cmd/GCS/main/AV_Rengoku_Akazo.lua",
        ["RMon"] = "https://raw.githubusercontent.com/Sendo-cmd/GCS/main/AV_Rengoku_Monarch.lua",
        ["BaseRGem"] = "https://raw.githubusercontent.com/Sendo-cmd/GCS/main/AV_REROLL_GEM.lua",
        ["BaseRIG"] = "https://raw.githubusercontent.com/Sendo-cmd/GCS/main/AV_REROLL_IGRIS.lua",
        ["LC"] = "https://raw.githubusercontent.com/Sendo-cmd/GCS/main/AV_IGRIS_Chain.lua",
        ["LCE"] = "https://raw.githubusercontent.com/Sendo-cmd/GCS/main/AV_IGRIS_ChainE.lua",
        ["LCEV"] = "https://raw.githubusercontent.com/Sendo-cmd/GCS/main/AV_IGRIS_ChainEV.lua",
        ["LS"] = "https://raw.githubusercontent.com/Sendo-cmd/GCS/main/AV_IGRIS_Sonj.lua",
        ["LSE"] = "https://raw.githubusercontent.com/Sendo-cmd/GCS/main/AV_IGRIS_SonjE.lua",
        ["LSEV"] = "https://raw.githubusercontent.com/Sendo-cmd/GCS/main/AV_IGRIS_SonjEV.lua",
        ["LSEM"] = "https://raw.githubusercontent.com/Sendo-cmd/GCS/main/AV_IGRIS_SonjEMon.lua",
        ["Marco"] = "https://raw.githubusercontent.com/Sendo-cmd/GCS/main/AV_Marco.lua",
        ["Log"] = "https://raw.githubusercontent.com/Sendo-cmd/GCS/main/AV_Log.lua",
        ["AutoBuyR"] = "https://raw.githubusercontent.com/Sendo-cmd/GCS/main/LobbyAV.lua",
        ["AutoBuyBE"] = "https://raw.githubusercontent.com/Sendo-cmd/GCS/main/LobbyAV.lua",
        ["AutoDelete"] = "https://raw.githubusercontent.com/Sendo-cmd/GCS/main/LobbyAV.lua",

    },
    [4509896324] = { --Anime-Last-Stand
        [5] = "https://raw.githubusercontent.com/Sendo-cmd/GCS/main/ALS_Reroll.lua",
        [6] = "https://raw.githubusercontent.com/Sendo-cmd/GCS/main/Reroll.lua",
    },
    [6149138290] = { --Anime-Card-Battle
        [1] = "https://raw.githubusercontent.com/Sendo-cmd/GCS/main/Banana.lua",
        [2] = "https://raw.githubusercontent.com/Sendo-cmd/GCS/main/ACB_Card.lua",
    }
}

Accounts = {
    ["FireBlackDevilZ"] = {
        1,
        2,
        4,
    },
    ["Champandbank147"] = {
        "LSEV",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["Nelida5865"] = {
        1,
        2,
    },
    ["xdyrdgyrdfg"] = {
        26,
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["maser080"] = {
        "RRengoku",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["Puggtopro"] = {
        "BaseB",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["Etaa_xm"] = {
        "BaseGemInf",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["OTeMoKungO"] = {
        "BaseGem",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["Nx_BlackLazy"] = {
        6,
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["aamlop1"] = {
        "BaseGem",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["Mynamefirstzz"] = {
        "BaseGem",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["B1za12345"] = {
        "RIgris",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["UMH_x7"] = {
        19,
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["djgodzz55"] = {
        "Gem2",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["Krv_kai43"] = {
        "Gem2",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["FalconWave21"] = {
        "BaseGem",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["comme009"] = {
        "BaseGem",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["SoulMossBats"] = {
        14,
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["Somrum11"] = {
        "BaseR",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["1accox"] = {
        "BaseGem",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["wexd45"] = {
        20,
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["GorgeousKeita"] = {
        "Gem3",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["XDGGZTheGod"] = {
        "LSEV",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["Xeonerct"] = {
        "BaseR",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["TKP_POT4X8"] = {
        "BaseGem",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["AFKFARMID"] = {
        "RIgris",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["NonBemmy"] = {
        "BaseB",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["YURIDRONEYET"] = {
        "RIgris",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["seuatiger9353"] = {
        "Gem2",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["xOFubukiOx"] = {
        26,
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["xMcTHx"] = {
        "RIgris",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["tanjiroxfire"] = {
        28,
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["thanwas009"] = {
        27,
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["notyuio111"] = {
        "BaseR",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["QAROBLOX060154"] = {
        "Gem3",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["EAzxc013"] = {
        "RIgris",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["okun474"] = {
        "RIgris",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["offj_0383"] = {
        "BaseB",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["HJRETAP"] = {
        "Gem3",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["GorgeousKeita"] = {
        "Gem3",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["aami1123"] = {
        29,
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["GymInsectDon"] = {
        25,
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["ASKINGZ12_43"] = {
        "RIgris",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["lnwterwowza"] = {
        "Gem2",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["TONKAORIKI_NEW"] = {
        "RIgris",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["narutoez441"] = {
        "BIgrisSon",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["salemam101"] = {
        19,
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["FormatDataNumber"] = {
        "RIgris",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["KleponBox"] = {
        "RIgris",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["nDBZyZsGMQOYMC0RE"] = {
        "LS",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["CAVIARHUB"] = {
        "BIgrisSon",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["Nonglud"] = {
        "BaseB",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["CGGG_TYUL2"] = {
        "Gem2",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["salldre"] = {
        "BaseB",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["Yanawarutkanpai"] = {
        "RIgris",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["M_Darknesss"] = {
        "RIgris",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["bluegamer1336"] = {
        "BaseR",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["KathryneU1368"] = {
        5,
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["AS1NR"] = {
        "BIgrisSon",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["ruihurtbeamkozer"] = {
        "BaseIG",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["LLAAKK122"] = {
        "LSE",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["paopaoforgame"] = {
        "RIgris",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["teerathornmoon"] = {
        "BaseB",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["RiceBing"] = {
        "RIgris",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["PinkheadFolk"] = {
        "Gem3",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["GoodxABA"] = {
        "BaseR",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["NachosMayo"] = {
        "Gem2",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["dufjr32"] = {
        "BaseB",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },
    ["Demonx_Hunt"] = {
        "BaseB",
        "Log",
        "Marco",
        "AutoBuyR",
        "AutoBuyBE",
    },

}

repeat task.wait() until game:IsLoaded()

local plr = game.Players.LocalPlayer
local Scripts = Games[game.gameId]
local Loaded = false
local Timer = 0
local ScriptLists = nil
for i,v in pairs(Accounts) do
    if i == plr.Name or i:lower() == plr.Name:lower() then
        ScriptLists = v
    end
end
for i,v in pairs(ScriptLists) do
    local ScriptUrl = Scripts[v];

    local ok, Functions = pcall(loadstring, game:HttpGet(ScriptUrl))

    if ok then
        Timer, Loaded = tick(), false
        task.spawn(function()
            Functions()
            Loaded = true
        end)

        repeat task.wait() until Loaded or (Timer - tick()) > 2
    end
end

